### ISSUE TITLE
createMergedStore not updating children

### ISSUE THREAD

**Issue by helfi92** [edriang/react-connect-context-hooks#6]
Hi,

I tried adding this library to a server side app built with next.js. I don't seem to be able to change page routes when using createMergedStore. The URL path change but the UI does not update with the new page. Is it possible this is happening because of React.memo? https://github.com/edriang/react-connect-context-hooks/blob/170be293a24e272d0a667378b2808f5deeeb0160/src/createMergedStore.tsx#L39

It works when I only use independent providers.

**Comment by adrian-marcelo-gallardo** [comment]
Hello @helfi92, thanks for reaching out.

Is it possible for you to share how you are using the `StoreProvider`?, e.g. by the docs:
```tsx
render(
  <StoreProvider onInit={[selection, onInit]}>
    <App />
  </StoreProvider>,
  document.getElementById('root')
)
```

Based on what you've pointed out in the source-code, I can see a problem in case the `children` of `StoreProvider` has some dynamic behavior.

As a quick workaround (and if possible for your app/use-case), I'd recommend moving whatever you have inside the `<StoreProvider>...</StoreProvider>` to a separate component (e.g. `<App  />`), and then just use it there, as in the example above (because the Memo is memoizing whatever thing it sees in the current component using the `StoreProvider`, but won't interfere if you encapsulate the logic within another component).

In the meantime (and for working on a real fix), could you please share some snippet of the Component code in which you are using `<StoreProvider>`?

**Comment by helfi92** [comment]
Hey @adrian-marcelo-gallardo, thanks for the quicky reply.

Here's my use case: I am trying to have 2 stores where the first one is a partial one and the second one has all of the combined reducers. The reason for this is performance. We want to have our landing page as fast as possible. Loading all of the reducers on the landing page runs a lot of javascript and is affecting many performance metrics.

Next.js provides a file [_app.js](https://nextjs.org/docs/advanced-features/custom-app) to initialize pages which is where most of the logic resides.

Here's some pseudo-code about my eventual plan:

```jsx
import {useRouter} from 'next/router';

function App(props) {
  const {Component} = props; 
  const router = useRouter();

  if (router.pathname === '/') {
    // PartialStore has reducerA, reducerB
    return (
      <PartialStore>
          <Component />
      </PartialStore>
    );
  }

  // FullStore has reducerA, reducerB, reducerC, reducerD
  return (
    <FullStore>
     <Component />
    </FullStore>
  );
}
```

Here's what I'm currently doing and that's not working as intended:

```jsx
function App(props) {
  const {Component} = props; 

  return (
      <PartialStore>
          <Component />
      </PartialStore>
  );
}
```

Next.js takes care of rendering _app so it's a bit hard to do `<PartialStore><App /></PartialStore>` since I don't have access to the instance.

**Comment by adrian-marcelo-gallardo** [comment]
@helfi92 thanks for providing those examples. I think I could reproduce the issue with this example:

```
const AppShell = () => {
  const [count, setCount] = React.useState(0);
  const onClick = () => setCount(prevCount => prevCount + 1);

  return (
    <StoreProvider onInit={[selection, onInit]}>
      <button onClick={onClick}>Count {count}</button>
      <App />
    </StoreProvider>
  )
}

render(
  <AppShell />,
  document.getElementById('root')
)
```

With this example I wanted to simulate the scenario in which a children of the `StoreProvider` (in this case the `button`) was changing its internal state but the UI didn't refreshed.

I just published a fix for this issue on Version `1.10.1`. If you can, please pull the changes and let me know if this solves your issue (and that everything else keeps working as expected).

Thank you.

**Comment by adrian-marcelo-gallardo** [comment]
Hi @helfi92, sorry to pinging you again.

I'm wondering if you had a chance to validate this yet, and/or if you have planned/scheduled to do this in the near future.

Otherwise I'll assume it is working and close the issue. Thanks in advance!

**Comment by helfi92** [comment]
Hey @adrian-marcelo-gallardo. Thank you so much for sending the patch. I plan to test it out hopefully during the weekend. I'll be sure to reach out soon with updates.

**Comment by helfi92** [comment]
Hey @adrian-marcelo-gallardo. Just wanted to let you know that it works perfectly now. Many thanks for looking into it. I appreciate it 🙏
