### ISSUE TITLE
Accepting object format for stateSelectors and actionSelectors

### ISSUE THREAD

**Issue by helfi92** [edriang/react-connect-context-hooks#7]
I'm currently working in migrating a large server side enterprise app that uses redux to react-connect-context-hooks. The main reason for this is to avoid having to load the full store on page load but rather do it incrementally. Dynamically adding reducers in redux is hard at the moment for server side rendering but looks promising with reat-connect-context-hooks. In order to do that, I was thinking of creating 2 stores, a tiny one for the landing page and a larger one to handle all the other pages.

We have a bunch of components/views like that:

```jsx
const reduxProps = ({profile, watchlist}) => ({
  email: profile.email,
  watchlistLength: watchlist.domains.length,
  admin: profile.admin,
  dev: profile.dev,
  reseller: profile.reseller,
  dappDev: profile.dappDev,
});
const connector = connect(reduxProps, {signOutUser: signOutUserRedux});

export default connector(MainDrawer);
```

In order to migrate them to react-connect-context-hooks, we would have to do the following similar change:

```jsx
export default withStore(MainDrawer, {
  stateSelectors: [
    'profile.email',
    'watchlist.domains.length:watchlistLength',
    'profile.admin',
    'profile.dev',
    'profile.reseller',
    'profile.dappDev'
  ],
  actionSelectors: ['auth.signOutUser: signOutUserRedux'],
});
```

Performing that change on all the 200+ components/views will be a bit painful. I was wondering if you were open to accepting objects for `stateSelectors` and `actionSelectors`. This would:
* be closer to the redux format so migrations are less painful
* make it harder to make mistakes (e.g., code editor will be able to help with you mistype state and action selectors

```jsx
export default withStore(MainDrawer, {
  stateSelectors: {
    email: profile.email,
    watchlistLength: watchlist.domains.length,
    admin: profile.admin,
    dev: profile.dev,
    reseller: profile.reseller,
    dappDev: profile.dappDev,
  },
  actionSelectors: {
    signOutUser: signOutUserRedux,
  },
});
```

Thanks!

**Comment by adrian-marcelo-gallardo** [comment]
Hey @helfi92, thanks for reaching by!

Actually, the selection mechanism supports three different flavors: array, object and function. You can check the documentation here: https://www.npmjs.com/package/react-connect-context-hooks#selections

I think you are looking for the `functional` approach; it receives the state and props, and from there you can programmatically return your selections.

As a side-note, both the array and object selectors are just "syntactic sugar" that internally gets compiled to the functional version when the store is created for performance improvements.

Let me know if that works for you!

**Comment by helfi92** [comment]
> As a side-note, both the array and object selectors are just "syntactic sugar" that internally gets compiled to the functional version when the store is created for performance improvements.

Good to know. Thanks, I wasn't aware of the three different flavors. That should be helpful.
