### ISSUE TITLE
Adding a store/reducer to an existent store

### ISSUE THREAD

**Issue by helfi92** [edriang/react-connect-context-hooks#8]
I'm currently working in migrating a large server side enterprise app that uses redux to react-connect-context-hooks. The main reason for this is to avoid having to load the full store on page load but rather do it incrementally. Dynamically adding reducers in redux is hard at the moment for server side rendering but looks promising with react-connect-context-hooks. In order to do that, I was thinking of creating 2 stores, a tiny one for the landing page and a larger one to handle all the other pages.

Is there a current way to add an additional store/reducer once a user navigate to a different page without losing the current state? For example, we would load storeA on the landing page then once the user navigates to a different page we would add storeB. This woud help reduce the amount of javsacript loaded on the landing page. Thanks!

**Comment by adrian-marcelo-gallardo** [comment]
Hello @helfi92! From what I understood from your question it's totally possible and it was the main intention for this Context-based approach.

As long as you never unmount the component holding your provider, then your state will remain as is (e.g. the root component).

On the other hand, if you navigate to different sections that are lazy-loaded, and them are wrapped on their own Provider, then you'll load that state on demand, and automatically "unload" that state when you navigate away (which I think it's what makes more sense to avoid have to manually clean-up the previous state).

If what you need is to preserve the store that was "unloaded", then that's not currently supported (out of the box). Is this the use-case you are trying to solve?

**Comment by helfi92** [comment]
> As long as you never unmount the component holding your provider, then your state will remain as is (e.g. the root component).

👌 Excellent
